spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: ${REDIS_TIMEOUT:3s}
redis:
  cache:
    ttl: ${REDIS_CACHE_TTL:1m}
opensearch:
  scheme: ${OPENSEARCH_SCHEME:http}
  host: ${OPENSEARCH_HOST:localhost}
  port: ${OPENSEARCH_PORT:9200}

logging:
  level:
    root: info
    com.aims.assembly: debug
    org.hibernate.SQL: debug
  file:
    path: ${LOG_PATH:logs/dev}

management:
  health:
    redis:
      enabled: true
    kafka:
      enabled: false
