package com.aims.assembly.domain.event;

import com.aims.assembly.domain.car.CarMaster;
import com.aims.assembly.domain.enums.EquipmentType;
import com.aims.assembly.domain.enums.ProcessCode;
import com.aims.assembly.domain.equipment.Equipment;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.jpa.test.autoconfigure.TestEntityManager;
import org.springframework.test.context.jdbc.Sql;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none"
})
@Sql(statements = {
        "DROP TABLE IF EXISTS manufacturing_event_json",
        "DROP TABLE IF EXISTS equipment",
        "DROP TABLE IF EXISTS car_master",
        "CREATE TABLE car_master (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, vehicle_id VARCHAR(50) NOT NULL, car_type VARCHAR(20) NOT NULL, engine_type VARCHAR(30) NOT NULL, car_color VARCHAR(30) NOT NULL, fuel_efficiency INT NULL, created_at TIMESTAMP NULL)",
        "CREATE TABLE equipment (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, process_code VARCHAR(20) NULL, equipment_code VARCHAR(50) NULL, equipment_name VARCHAR(100) NULL, equipment_type VARCHAR(50) NULL, created_at TIMESTAMP NULL)",
        "CREATE TABLE manufacturing_event_json (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id VARCHAR(100) NOT NULL, event_time TIMESTAMP NOT NULL, car_master_id BIGINT NOT NULL, equipment_id BIGINT NOT NULL, process_code VARCHAR(20) NOT NULL, station_code VARCHAR(50), equipment_code VARCHAR(50) NOT NULL, equipment_type VARCHAR(50), equipment_status VARCHAR(30), event_type VARCHAR(50), event_json JSON NOT NULL, is_sent BOOLEAN DEFAULT FALSE, sent_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_manufacturing_event_json_car_master FOREIGN KEY (car_master_id) REFERENCES car_master(id), CONSTRAINT fk_manufacturing_event_json_equipment FOREIGN KEY (equipment_id) REFERENCES equipment(id))"
})
@DisplayName("제조 이벤트 JSON 엔티티 JPA 매핑 테스트")
class ManufacturingEventJsonJpaTest {

    @Autowired
    private TestEntityManager entityManager;

    @Test
    @DisplayName("제조 이벤트 JSON을 저장하면 차량과 설비 연관관계, JSON 값, 발송 상태가 함께 저장된다")
    void persistManufacturingEventJson() {
        CarMaster carMaster = entityManager.persist(createCarMaster());
        Equipment equipment = entityManager.persist(createEquipment());

        ManufacturingEventJson event = ManufacturingEventJson.builder()
                .eventId("EVT-20260617-003")
                .eventTime(LocalDateTime.of(2026, 6, 17, 12, 0))
                .carMaster(carMaster)
                .equipment(equipment)
                .processCode(ProcessCode.PAINT)
                .stationCode("PAINT-ST-01")
                .equipmentCode("CAMERA-001")
                .equipmentType("CAMERA")
                .equipmentStatus("NORMAL")
                .eventType("QUALITY_CHECKED")
                .eventJson(JsonNodeFactory.instance.objectNode()
                        .put("surfaceQualityScore", 97.5)
                        .put("defectCount", 0))
                .build();

        ManufacturingEventJson saved = entityManager.persistFlushFind(event);

        assertAll(
                () -> assertNotNull(saved.getId()),
                () -> assertEquals("EVT-20260617-003", saved.getEventId()),
                () -> assertEquals(carMaster.getId(), saved.getCarMaster().getId()),
                () -> assertEquals(equipment.getId(), saved.getEquipment().getId()),
                () -> assertEquals(ProcessCode.PAINT, saved.getProcessCode()),
                () -> assertEquals(97.5, saved.getEventJson().get("surfaceQualityScore").asDouble()),
                () -> assertEquals(0, saved.getEventJson().get("defectCount").asInt()),
                () -> assertFalse(saved.getIsSent()),
                () -> assertNotNull(saved.getCreatedAt()),
                () -> assertNotNull(saved.getUpdatedAt())
        );
    }

    private CarMaster createCarMaster() {
        return CarMaster.builder()
                .vehicleId("VH-003")
                .carType("SUV")
                .engineType("HYBRID")
                .carColor("BLUE")
                .fuelEfficiency(18)
                .build();
    }

    private Equipment createEquipment() {
        return Equipment.builder()
                .processCode(ProcessCode.PAINT)
                .equipmentCode("CAMERA-001")
                .equipmentName("Paint Inspection Camera")
                .equipmentType(EquipmentType.CAMERA)
                .build();
    }
}
